site_name:        EventSimulation.jl
repo_url:         https://github.com/bkamins/EventSimulation.jl
site_description: Event based Discrete Event Simulator
site_author:      Bogumił Kamiński

theme: readthedocs

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code

docs_dir: 'build'

pages:
  - Home: index.md
  - Tutorial: tutorial.md
  - Reference: reference.md
